### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by williamboman** [sibbell/sibbell-issues#14]
How do I delete my account from Sibbell?

**Comment by davegaeddert** [comment]
@williamboman I can delete it for you (you're the first person to ask). Do you want me to go ahead and delete it?

**Comment by williamboman** [comment]
@davegaeddert Yeah that would be great :smile:.

**Comment by davegaeddert** [comment]
@williamboman I went ahead and deleted your account. Mind if I ask what you thought of Sibbell? Did you have any issues?

**Comment by williamboman** [comment]
Didn't have any issues, it was just not what I was looking for

**Comment by davegaeddert** [comment]
Ok cool. Just out of curiosity, what were you looking for? I'm always working on new features and trying to figure out what direction to take things...

**Comment by williamboman** [comment]
The fact that it just automatically watches my starred and watched repositories. I'm not interested in 95% of those. I was looking for a service that would notify me when a repo that I sort of manually specify releases a new version :).

**Comment by davegaeddert** [comment]
So this feature isn't very well publicized probably, but in the menu there's a link to "Manage Repos":

![screen shot 2015-05-20 at 4 48 11 pm](https://cloud.githubusercontent.com/assets/649496/7737366/26cd9094-ff10-11e4-8b60-9f57bd427620.png)

There you can individually enable/disable specific repos. So in settings you could turn off both stars and watching, then go enable just the ones you want on https://sibbell.com/github/repos/.

![screen shot 2015-05-20 at 4 49 59 pm](https://cloud.githubusercontent.com/assets/649496/7737378/48b6a81c-ff10-11e4-8600-30b5fbb44a99.png)
![screen shot 2015-05-20 at 4 47 58 pm](https://cloud.githubusercontent.com/assets/649496/7737450/dfa0944a-ff10-11e4-8e56-4e443f5f2e01.png)

This just recently got built because someone else asked for it (#3). I should also mention it is one of the few paid features -- but the price for it is as low as it could be ($2 / month). I know nobody likes paying for stuff, but I hope it's cheap enough that it's not a huge hurdle for people.
