### ISSUE TITLE
Not getting email when a new release is available

### ISSUE THREAD

**Issue by reqr27** [sibbell/sibbell-issues#29]
I'm starred in some projects, but i'm not getting the notification when a release is available

**Comment by davegaeddert** [comment]
Hey @reqr27, it looks like you have 2 starred repos (https://github.com/stars/reqr27) but neither of them have had releases since you created your account yesterday. Sibbell only sends a notification for new [releases](https://help.github.com/articles/about-releases/), not pushes to the repo or anything else...

https://github.com/appium/appium/releases
https://github.com/Enmanuel07/FinalMineria/releases

Does that make sense? Am I missing something? We were also going through some server migration yesterday, so it is possible that something got missed.

**Comment by jcbvm** [comment]
I have the same problem and my account was created before new releases were released (ember-cli for example).

**Comment by davegaeddert** [comment]
Hey @jcbvm, is this the specific repo you meant as the example - https://github.com/ember-cli/ember-cli/releases?

**Comment by jcbvm** [comment]
@davegaeddert yes

**Comment by jcbvm** [comment]
Got an email this evening from a release of the ember project, so it seems to be working now.

**Comment by davegaeddert** [comment]
Glad to hear it @jcbvm, Sibbell does a *ton* of API calls and background processing with GitHub and sometimes it starts to fall behind as things pile up. Fortunately I was able to make quite a few optimizations this week to speed things up, so thanks for mentioning something!
