### ISSUE TITLE
Can I choose the repositories I want to subscribe?

### ISSUE THREAD

**Issue by scarletsky** [sibbell/sibbell-issues#3]
Thanks for the great projects.
I have star 400+ repos in github, and I recently receive lots of email sending by sibbell . In fact, I DON'T need to know EVERY repositoriy's new release notification. I just want to know the repositories that I am interested NOW, not the past.

I have looked the settings on sibbell.com, but it seems there is no way to do that.
So, what should I do ?
Thanks.

**Comment by davegaeddert** [comment]
Hey @scarletsky, you're right, currently there's not a way within Sibbell to choose which of your starred repos you want to receive notifications for. I have thought about adding that though. Just out of curiosity, is there a reason you don't want to un-star them in GitHub?

**Comment by scarletsky** [comment]
@davegaeddert 
Yep, if I think the repo is interesting or useful, I will star it. Although it is not helpful for me now, it do not means that it will not help me in the future. 
Also, staring a repo gives your respect to the repo's author, don't you think so? :smiley: :

**Comment by davegaeddert** [comment]
Agreed @scarletsky! I actually use stars a similar way myself, just wanted to probe a little. Thanks for taking the time to create an issue around this, I'll see what I can do.

**Comment by scarletsky** [comment]
@davegaeddert 
Fighting ! :grin:

**Comment by maxtepkeev** [comment]
+1 on that feature

**Comment by davegaeddert** [comment]
Alright I took a first crack at it. It should be showing up shortly and you should be able to find a "Manage Repos" menu item soon. Let me know how it goes!

![image](https://cloud.githubusercontent.com/assets/649496/7059769/ddb7b97e-de3b-11e4-8786-ace796994097.png)
![image](https://cloud.githubusercontent.com/assets/649496/7059779/f0f0d3a4-de3b-11e4-8c26-2999ff2af580.png)

**Comment by scarletsky** [comment]
Awesome! Try it now!

**Comment by scarletsky** [comment]
@davegaeddert 
I have one question on [Settings page](http://sibbell.com/settings/) and [Manage repos page](http://sibbell.com/github/repos/).

If I set `sync` to `off` in Starred on Settings page, what will happen? I try it, but on the Manage repos page, I see the repos shows ON...

![98c2b76b-1538-4155-bfcc-4a8f128161e7](https://cloud.githubusercontent.com/assets/2386165/7059991/f3da2f50-deab-11e4-9041-cb4644eb01f5.png)
![84550b4b-9770-41fa-8c9c-4e6c3cb54de0](https://cloud.githubusercontent.com/assets/2386165/7059990/f2e6a970-deab-11e4-95f0-dab4acfd5336.png)

**Comment by maxtepkeev** [comment]
Hi!

Awesome! Thanks for such a quick action.

I have the same question as @scarletsky and also I have one suggestion, make a switcher to turn all repos off/on, because at the moment they are all switched on and I have to uncheck all repos that I don't want to be notified for. That isn't very convenient in my opinion if I want to be notified only for some repos, so I would like to first uncheck all of them and then just check only some that I'm currently interested in.

Thanks!

**Comment by davegaeddert** [comment]
Hey guys, thanks for letting me know. I did it in a bit of a hurry last night since I had a few hours, but it looks like I've got some Redis configuration that needs to be cleaned up.

I think it's working now. What it is *supposed* to do is this:
- if you switch starred/watching from `off` to `on` and hit save, then notifications will be enabled for all of the starred/watching
- if you switch starred/watching from `on` to `off` and hit save, then notifications will be disabled for all of the starred/watching

So it only happens when you change the setting from what it was previously (otherwise every time you hit save you would reset all your settings). Does that make sense?

@scarletsky if you turn starred to `on` and hit save, then turn it to `off` and hit save, all of your starred ones should be turned off.
@maxtepkeev if you don't want to enable them all be default, you can switch starred and watching to `off` and then pick the individual ones.

**Comment by maxtepkeev** [comment]
Hey Dave,

Cool, thanks! That makes perfect sense.

I have one more suggestion though, I believe that I shouldn't see my own repos in the list of managed repos, I mean, what's the point for me to receive notifications for me own releases ;-)

Thanks for you work!

**Comment by davegaeddert** [comment]
Thanks @maxtepkeev. Feel free to make a new issue for that, not sure it ranks super high in priority for me, but it would be pretty easy to do and I'd love to hear how other people feel!

**Comment by scarletsky** [comment]
@davegaeddert 
I receive lots of emails from sibbell.com just now, even though the latest version of the repo release months ago.
I don't know why.  Maybe it is related to I reset the settings days ago ?

**Comment by davegaeddert** [comment]
Thanks @scarletsky, it looks like something happened system-wide. I'll try and see if I can figure out what went wrong...

**Comment by davegaeddert** [comment]
Hey @scarletsky and @maxtepkeev, I'm working on ways to monetize Sibbell - the primary reason being the fact that I don't want to cover the hosting costs forever. One idea I'm playing around with is adding features that can be independently enabled, each with their own really low monthly costs ($1 or $2 each). Sibbell itself would still have a completely free tier that will do almost everything it does today (and probably more). The additional paid features would be more for the "power users". The reason I mention all this is because I think the ability to manage the notifications for individual repos could be one of these paid features. So I'm curious, would you pay $2 a month to have this functionality?

(P.S. if I move forward with something like this, I'll try and find a way to keep it free for you)

**Comment by scarletsky** [comment]
I still don't understand what you want to do, but I don't care the cost if the service is really useful for me.

But if you want to do some paid features, you should investigate your competition, and then make your paid features better than them. If you can, I think "power users" will glad to pay for you.

**Comment by maxtepkeev** [comment]
Hi Dave,

Would I pay $2 a month to have access to individual repos functionality?

If you ask me personally, then the answer is no. Why? Because I use it only for my own open source project, i.e. I have a project which unifies some functionality for different Python ORMs and I want to know when a new version of an ORM that I support is released to check that my own software still works with this new version. So if I don't make money from my own software, why would I pay for this notifications, I can just write some simple cron script that will do that for me every day.

But that's just me, in general I believe it depends on different factors, e.g. whether you (not you but some abstract person ;-)) make money yourself with the help of your service somehow, or maybe you're just a lazy person and instead of writing your own simple cron script, you will better pay 2$ and use some service that just works. So I believe there is no easy answer to your question, but I agree with @scarletsky that before making decisions you should investigate the competitive services (if any). And again, in general 1$ or 2$ isn't a big sum of money so probably a lot of people will be able to pay.

Hope that helps.
