### ISSUE TITLE
Sync not working properly.

### ISSUE THREAD

**Issue by ChillarAnand** [sibbell/sibbell-issues#36]
Repo A is is starred & watching by me.
If i turn off syncing for starred & turn on syncing for wathcing, repo a is not synced.

**Comment by davegaeddert** [comment]
Hey @ChillarAnand, I'll have to take a look at this and make sure there's nothing wrong with it. If you take a look now, does the repo you're talking about show as synced? Sibbell does a lot of background processing (since it has to use the GitHub APIs most of the time), so the changes may have gone through but not *immediately*.

**Comment by ChillarAnand** [comment]
Yep.
